stages:
  - build-frontend
  - build-backend

frontend:
  stage: build-frontend
  image: node:22
  before_script:
    - cd frontend
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/build
    expire_in: 1 week
  only:
    - master

backend:
  stage: build-backend
  image: maven:3.9.6-eclipse-temurin-17
  before_script:
    - cd backend
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - backend/target/*.jar
    expire_in: 1 week
  needs: ["frontend"]
  only:
    - master
